Add Jaccard index
hbollon/go-edlib pull request #9
Opened 2021-08-31 08:48 UTC by ShriprajwalK

Adds Jaccard index as mentioned in #8

2021-08-31 08:51 UTC, ShriprajwalK commented
Hi @hbollon, I've added code for finding the Jaccard index. Do let me know if I can improve it somehow or if there are any changes to be made.

2021-08-31 11:25 UTC, hbollon requested changes
Thanks for your PR! I will review it ASAP
In the meantime, I checked quickly and I noticed that you doesn't added your Jaccard function to `StringSimilarity` one (located in `string-analysis.go`), can you add it please?

2021-09-01 06:22 UTC, ShriprajwalK commented
I've added the Jaccard function to `string-analysis.go` and `string-analysis_test.go`. Are the changes made there alright?

2021-09-01 16:06 UTC, hbollon requested changes

2021-09-01 16:06 UTC, hbollon commented on string-analysis_test.go
> +		{"Jaccard : No characters match", args{"abcd", "effgghh", Cosine}, 0.0, false},
Idk if this case is useful for Jaccard but anyways it use Cosine algorithm instead of Jaccard one

2021-09-01 16:08 UTC, hbollon commented
Other than that everything looks good to me :smile: 
However, I must make some modifications to the Ci workflow of this repo and take the time to test the algo before merging.
I'm trying to do this quickly! :wink:

2021-09-01 18:05 UTC, ShriprajwalK commented
Made the changes. Thanks a lot!

2021-09-06 19:50 UTC, hbollon approved these changes

2021-09-06 19:57 UTC, merged

2021-09-06 19:57 UTC, hbollon commented
It's merged! Thanks for your contribution mate! :smile: